import * as THREE from 'three';
import './style.css';
import { BOARD_LINKS, boardPosition, createGame, takeTurn } from './game.js';

const $ = (s) => document.querySelector(s);
const canvas = $('#scene');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.25;
const scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(0x080916, .025);
const camera = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, .1, 180); camera.position.set(15, 17, 19); camera.lookAt(0, 0, 0);
scene.add(new THREE.HemisphereLight(0x8899ff, 0x18061f, 1.5));
const key = new THREE.DirectionalLight(0xffddf3, 5); key.position.set(-9, 18, 8); key.castShadow = true; key.shadow.mapSize.set(2048, 2048); scene.add(key);
const magenta = new THREE.PointLight(0xff238d, 30, 28); magenta.position.set(9, 5, -3); scene.add(magenta);
const cyan = new THREE.PointLight(0x21ffe1, 25, 24); cyan.position.set(-8, 4, 5); scene.add(cyan);

const world = new THREE.Group(); world.rotation.y = -.12; scene.add(world);
const tileGeo = new THREE.BoxGeometry(1.06, .18, 1.06); const tileMats = [];
for (let i=0;i<4;i++) tileMats.push(new THREE.MeshPhysicalMaterial({color:[0x171936,0x202448,0x241539,0x132f38][i],roughness:.28,metalness:.46,clearcoat:1,emissive:[0x07091a,0x091127,0x120619,0x051b1b][i]}));
function coords(square, y=.2) { if (!square) return new THREE.Vector3(-6.3,y,5); const {row,col}=boardPosition(square); return new THREE.Vector3((col-4.5)*1.12,y,(4.5-row)*1.12); }
for(let n=1;n<=100;n++){const {row,col}=boardPosition(n);const m=new THREE.Mesh(tileGeo,tileMats[(row+col)%4]);m.position.copy(coords(n,.02));m.castShadow=m.receiveShadow=true;world.add(m);const spr=numberSprite(n);spr.position.copy(coords(n,.145));spr.rotation.x=-Math.PI/2;world.add(spr)}
const base = new THREE.Mesh(new THREE.BoxGeometry(12.1,.35,12.1),new THREE.MeshPhysicalMaterial({color:0x090b1c,metalness:.7,roughness:.2,clearcoat:1}));base.position.y=-.22;base.receiveShadow=true;world.add(base);
function numberSprite(n){const c=document.createElement('canvas');c.width=c.height=96;const x=c.getContext('2d');x.font='600 27px Space Grotesk, sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillStyle=n===100?'#76ffec':'#9296b4';x.fillText(n,48,48);const tex=new THREE.CanvasTexture(c);const mat=new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false});const s=new THREE.Sprite(mat);s.scale.set(.48,.48,.48);return s}
function addLadder(a,b){const p1=coords(a,.25),p2=coords(b,.25),d=p2.clone().sub(p1),len=d.length(),mid=p1.clone().add(p2).multiplyScalar(.5),angle=Math.atan2(d.x,d.z);const g=new THREE.Group();g.position.copy(mid);g.rotation.y=angle;const mat=new THREE.MeshStandardMaterial({color:0xffc34e,emissive:0x6b2700,emissiveIntensity:.8,metalness:.72,roughness:.2});for(const x of [-.18,.18]){const rail=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,len,8),mat);rail.rotation.x=Math.PI/2;rail.position.x=x;g.add(rail)}for(let z=-len/2+.18;z<len/2;z+=.3){const rung=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,.36,7),mat);rung.rotation.z=Math.PI/2;rung.position.z=z;g.add(rung)}world.add(g)}
function addChute(a,b){const p1=coords(a,.3),p2=coords(b,.3),curve=new THREE.CatmullRomCurve3([p1,p1.clone().lerp(p2,.32).add(new THREE.Vector3(.6,.55,.25)),p1.clone().lerp(p2,.66).add(new THREE.Vector3(-.55,.25,-.2)),p2]);const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,28,.115,10,false),new THREE.MeshPhysicalMaterial({color:0xff3b80,emissive:0x7b002c,emissiveIntensity:1.5,metalness:.35,roughness:.18,clearcoat:1}));world.add(tube)}
Object.entries(BOARD_LINKS).forEach(([a,b])=>b>a?addLadder(+a,b):addChute(+a,b));
const ring=new THREE.Mesh(new THREE.TorusGeometry(7.7,.025,6,120),new THREE.MeshBasicMaterial({color:0x6746ff,transparent:true,opacity:.45}));ring.rotation.x=Math.PI/2;ring.position.y=-.02;world.add(ring);
const particleGeo=new THREE.BufferGeometry(),pos=new Float32Array(500*3);for(let i=0;i<pos.length;i+=3){pos[i]=(Math.random()-.5)*38;pos[i+1]=Math.random()*18;pos[i+2]=(Math.random()-.5)*38}particleGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));const particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({color:0xa982ff,size:.045,transparent:true,opacity:.75}));scene.add(particles);
const colors=[0x67ffe5,0xff4ba7,0xffcf56,0x856eff],pieces=[];for(let i=0;i<4;i++){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.28,5,10),new THREE.MeshPhysicalMaterial({color:colors[i],emissive:colors[i],emissiveIntensity:.4,metalness:.35,roughness:.2,clearcoat:1}));body.castShadow=true;g.add(body);const glow=new THREE.PointLight(colors[i],2.5,2.5);g.add(glow);g.position.copy(coords(0,.45)).add(new THREE.Vector3(i*.25,0,0));world.add(g);pieces.push(g)}

let game=createGame(4),playing=false,busy=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,soundOn=true,audio;
const faces=['⚀','⚁','⚂','⚃','⚄','⚅'];
function renderPlayers(){ $('#players').innerHTML=game.players.map((p,i)=>`<div class="player ${i===game.current&&game.winner===null?'active':''}" style="--color:#${colors[i].toString(16).padStart(6,'0')}"><i class="dot"></i><strong>${p.name}</strong><span>${p.square}</span></div>`).join(''); }
function setStatus(title,detail){$('#status').textContent=title;$('#detail').textContent=detail;$('#round').textContent=`TURN ${game.turns+1}`}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
function initAudio(){if(audio)return;const C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C()}
function beep(freq=440,d=.12,type='sine'){if(!soundOn||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.4,audio.currentTime+d);g.gain.setValueAtTime(.1,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
const wait=(ms)=>new Promise(r=>setTimeout(r,reduced?Math.min(ms,30):ms));
async function tweenPiece(piece,from,to,duration=300){if(reduced){piece.position.copy(to);return}await new Promise(resolve=>{const start=performance.now();function frame(now){const t=Math.min(1,(now-start)/duration),e=1-(1-t)**3;piece.position.lerpVectors(from,to,e);piece.position.y=to.y+Math.sin(t*Math.PI)*.32;if(t<1)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)})}
async function animateMove(index,start,move){const piece=pieces[index];if(move.landing!==start){for(let s=start+1;s<=move.landing;s++){const target=coords(s,.48).add(new THREE.Vector3((index%2-.5)*.18,0,(Math.floor(index/2)-.5)*.18));await tweenPiece(piece,piece.position.clone(),target,145);beep(260+s*4,.035,'triangle')}}if(move.link){toast(move.link==='ladder'?'LADDER BOOST!':'CHUTE DROP!');beep(move.link==='ladder'?620:180,.35,'sawtooth');await tweenPiece(piece,piece.position.clone(),coords(move.final,.48).add(new THREE.Vector3((index%2-.5)*.18,0,(Math.floor(index/2)-.5)*.18)),700)}}
async function performTurn(){if(busy||game.winner!==null)return;busy=true;$('#roll').disabled=true;initAudio();const player=game.current,start=game.players[player].square,roll=1+Math.floor(Math.random()*6);$('#roll').classList.add('rolling');for(let i=0;i<8;i++){await wait(55);$('#die-face').textContent=faces[Math.floor(Math.random()*6)]}$('#die-face').textContent=faces[roll-1];$('#roll').classList.remove('rolling');beep(380+roll*35,.16);const next=takeTurn(game,roll);await animateMove(player,start,next.lastMove);game=next;renderPlayers();if(game.winner!==null){setStatus(game.winner===0?'You conquered the board!':`${game.players[game.winner].name} wins`,`${game.turns} turns decided this match.`);toast('SQUARE 100 — VICTORY');for(let n=0;n<5;n++){beep(500+n*110,.2);await wait(90)}busy=false;return}const p=game.players[game.current];setStatus(game.current===0?'Your move':`${p.name} is rolling`,game.current===0?'Roll the die and bend your fate.':'The arena chooses their path.');busy=false;if(game.current===0){$('#roll').disabled=false;$('#roll-label').textContent='TAP TO ROLL'}else{$('#roll-label').textContent='RIVAL TURN';await wait(720);performTurn()}}
function reset(){game=createGame(4);pieces.forEach((p,i)=>p.position.copy(coords(0,.45)).add(new THREE.Vector3(i*.25,0,0)));renderPlayers();setStatus('Your move','Roll the die and bend your fate.');$('#roll').disabled=false;$('#die-face').textContent='⚄';$('#roll-label').textContent='TAP TO ROLL'}
$('#start').onclick=()=>{playing=true;initAudio();beep(330,.3);$('#hero').hidden=true;$('#game').hidden=false;reset()};$('#roll').onclick=performTurn;$('#restart').onclick=reset;$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').setAttribute('aria-pressed',String(!soundOn));$('#sound').textContent=soundOn?'♪':'×'};$('#motion').onclick=()=>{reduced=!reduced;$('#motion').setAttribute('aria-pressed',String(reduced))};
function loop(t){particles.rotation.y=t*.00002;if(!reduced){world.position.y=Math.sin(t*.0006)*.05;ring.rotation.z=t*.00008}const target=playing?new THREE.Vector3(10.2,15,13.5):new THREE.Vector3(15,17,19);camera.position.lerp(target,.025);camera.lookAt(playing?new THREE.Vector3(0,0,0):new THREE.Vector3(-1,1,0));renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderPlayers();
